Update python-greetings.yml

diff --git a/.github/workflows/python-greetings.yml b/.github/workflows/python-greetings.yml
--- a/.github/workflows/python-greetings.yml
+++ b/.github/workflows/python-greetings.yml
@@ -64,17 +64,24 @@ jobs:
         uses: actions/checkout@v3.5.2
         with:
           repository: mtararujs/course-js-api-framework
-          path: python-greetings
+          path: course-js-api-framework
       - name: Install npm dependencies
         run: |
           npm install
+          pm2 status
           echo "Installed npm dependencies."
-        working-directory: python-greetings
+        working-directory: course-js-api-framework
+      - name: Check if greetings-app-dev is running
+        run: |
+          if ! pm2 describe greetings-app-dev &>/dev/null; then
+            echo "Error: greetings-app-dev is not running."
+            exit 1
+          fi
       - name: Run tests on Dev
         run: |
           echo "Running tests on Dev..."
-          npm run greetings greetings_dev
-        working-directory: python-greetings
+          npm run greetings greetings_dev -- --port 7001
+        working-directory: course-js-api-framework
 
   deploy-to-staging:
     runs-on: self-hosted
